apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-ping
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            args:
            - /bin/sh
            - -c
            - curl http://{{ .Release.Name }}-service:{{ .Values.service.port }}
          restartPolicy: OnFailure