apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
      - name: flask-container
        image: barakzak/quakewatch:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: quakewatch-config
        - secretRef:
            name: quakewatch-secret
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/app.log
          subPath: app.log
      volumes:
      - name: logs
        emptyDir: {}